Element["" "" "" "" 1000 1000 0 7874 0 100 ""]
(
    # Screw hole.
    # Generated by landmaker 2014-07-21
    # Copyright 2014 David B. Curtis
    # Plugin: hole
    # Parameters: 
    #   pad=7 mm
    #   fit=free
    #   drill=3 mm
    # rules:
    #   maskrelief = 4 mil
    #   minspace = 8 mil
    #   refdessize = 40 mil
    Pin[0 0 27559 1600 28359 12500 "1" "1" ""]
)
