Element["" "" "" "" 1000 1000 0 7874 0 100 ""]
(
    # Screw hole.
    # Generated by landmaker 2014-07-21
    # Copyright 2014 David B. Curtis
    # Plugin: hole
    # Parameters: 
    #   pad=45 mil
    #   fit=free
    #   drill=0.02 inch
    # rules:
    #   maskrelief = 4 mil
    #   minspace = 8 mil
    #   refdessize = 40 mil
    Pin[0 0 4500 1600 5300 2000 "1" "1" ""]
)
