Element["" "" "" "" 1000 1000 0 7874 0 100 ""]
(
    # Alpha RE130F encoder.
    # Generated by landmaker 2014-07-27
    # Copyright 2014 David B. Curtis
    # Plugin: enc
    # Parameters: 
    #   type=RE130F
    # rules:
    #   maskrelief = 4 mil
    #   minspace = 8 mil
    #   annulus_hs = 20 mil
    #   refdessize = 40 mil
    # Pins 6 & 7 are case.
    Pin[-27500 -10000 8200 1600 9000 4200 "1" "1" ""]
    Pin[-27500 10000 8200 1600 9000 4200 "2" "2" ""]
    Pin[29500 10000 8200 1600 9000 4200 "3" "3" ""]
    Pin[29500 0 8200 1600 9000 4200 "4" "4" ""]
    Pin[29500 -10000 8200 1600 9000 4200 "5" "5" ""]
    Pin[0 26000 12600 1600 13400 8599 "6" "6" ""]
    Pin[0 -26000 12600 1600 13400 8599 "7" "7" ""]
    ElementLine[26000 -24500 7000 -24500 1000]
    ElementLine[26000 -24500 26000 -15000 1000]
    ElementLine[-26000 24500 -7000 24500 1000]
    ElementLine[-26000 24500 -26000 15000 1000]
    ElementLine[26000 24500 7000 24500 1000]
    ElementLine[26000 24500 26000 15000 1000]
    ElementLine[-26000 -24500 -7000 -24500 1000]
    ElementLine[-26000 -24500 -26000 -15000 1000]
)
