Element["" "" "" "" 1000 1000 0 7874 0 100 ""]
(
    # Molex 54819-0519 USB connector.
    # Generated by landmaker 2014-07-28
    # Copyright 2014 David B. Curtis
    # Plugin: usbconnmolex
    # Parameters: 
    #   type=54819-0519
    # rules:
    #   maskrelief = 4 mil
    #   minspace = 8 mil
    #   minannulus = 10 mil
    #   refdessize = 40 mil
    #   minsilk = 10 mil
    # Pins 6 & 7 are case.
    # complex drilled pad for pin #1
    Pin[0 -6299 4133 0 0 2800 "1" "1" ""]
    Pad[0 -6299 0 -6299 4133 2399 4933 "1" "1" ""]
    Pad[0 -6299 2362 -6299 4133 2399 4933 "1" "1" "onsolder"]
    # complex drilled pad for pin #2
    Pin[-4724 -3149 4133 0 0 2800 "2" "2" ""]
    Pad[-4724 -3149 -4724 -3149 4133 2399 4933 "2" "2" ""]
    Pad[-7086 -3149 -4724 -3149 4133 2399 4933 "2" "2" "onsolder"]
    # complex drilled pad for pin #3
    Pin[0 0 4133 0 0 2800 "3" "3" ""]
    Pad[0 0 0 0 4133 2399 4933 "3" "3" ""]
    Pad[0 0 2362 0 4133 2399 4933 "3" "3" "onsolder"]
    # complex drilled pad for pin #4
    Pin[-4724 3149 4133 0 0 2800 "4" "4" ""]
    Pad[-4724 3149 -4724 3149 4133 2399 4933 "4" "4" ""]
    Pad[-7086 3149 -4724 3149 4133 2399 4933 "4" "4" "onsolder"]
    # complex drilled pad for pin #5
    Pin[0 6299 4133 0 0 2800 "5" "5" ""]
    Pad[0 6299 0 6299 4133 2399 4933 "5" "5" ""]
    Pad[0 6299 2362 6299 4133 2399 4933 "5" "5" "onsolder"]
    Pin[-19881 -14370 10629 1600 11429 8599 "6" "6" ""]
    Pin[-19881 14370 10629 1600 11429 8599 "7" "7" ""]
    # Keep Out
    ElementLine[-7086 -11811 -7086 -17322 1000]
    ElementLine[-7086 -17322 2755 -17322 1000]
    ElementLine[2755 -17322 2755 -11811 1000]
    ElementLine[2755 -11811 -7086 -11811 1000]
    ElementLine[-7086 -11811 2755 -17322 1000]
    ElementLine[2755 -11811 -7086 -17322 1000]
    # Keep Out
    ElementLine[-7086 17322 -7086 11811 1000]
    ElementLine[-7086 11811 2755 11811 1000]
    ElementLine[2755 11811 2755 17322 1000]
    ElementLine[2755 17322 -7086 17322 1000]
    ElementLine[-7086 17322 2755 11811 1000]
    ElementLine[2755 17322 -7086 11811 1000]
    # Keep Out
    ElementLine[-26771 11811 -26771 -11811 1000]
    ElementLine[-26771 -11811 -25196 -11811 1000]
    ElementLine[-25196 -11811 -25196 11811 1000]
    ElementLine[-25196 11811 -26771 11811 1000]
    ElementLine[-26771 11811 -25196 -11811 1000]
    ElementLine[-25196 11811 -26771 -11811 1000]
    # Keep Out
    ElementLine[-25196 8661 -25196 -8661 1000]
    ElementLine[-25196 -8661 -22047 -8661 1000]
    ElementLine[-22047 -8661 -22047 8661 1000]
    ElementLine[-22047 8661 -25196 8661 1000]
    ElementLine[-25196 8661 -22047 -8661 1000]
    ElementLine[-22047 8661 -25196 -8661 1000]
)
